import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
import Script from 'next/script';
import '../public/assets/bootstrap/css/bootstrap.min.css';
import '../public/assets/css/owl.carousel.css';
import '../public/assets/css/magnific-popup.css';
import '../public/assets/css/animate.css';
import '../public/assets/css/meanmenu.min.css';
import '../public/assets/css/main.css';
import '../public/assets/css/responsive.css';
import '../public/assets/css/all.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
